/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.algorist.art.view.display;

/**
 *
 * @author Asus
 */
public class ExportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExportPanel
     */
    public ExportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelGIF = new javax.swing.JPanel();
        jPanelJPEG = new javax.swing.JPanel();
        jPanelPNG = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanelSalvar = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelGIFLayout = new javax.swing.GroupLayout(jPanelGIF);
        jPanelGIF.setLayout(jPanelGIFLayout);
        jPanelGIFLayout.setHorizontalGroup(
            jPanelGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanelGIFLayout.setVerticalGroup(
            jPanelGIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("GIF", jPanelGIF);

        javax.swing.GroupLayout jPanelJPEGLayout = new javax.swing.GroupLayout(jPanelJPEG);
        jPanelJPEG.setLayout(jPanelJPEGLayout);
        jPanelJPEGLayout.setHorizontalGroup(
            jPanelJPEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanelJPEGLayout.setVerticalGroup(
            jPanelJPEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("JPEG", jPanelJPEG);

        javax.swing.GroupLayout jPanelPNGLayout = new javax.swing.GroupLayout(jPanelPNG);
        jPanelPNG.setLayout(jPanelPNGLayout);
        jPanelPNGLayout.setHorizontalGroup(
            jPanelPNGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanelPNGLayout.setVerticalGroup(
            jPanelPNGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PNG", jPanelPNG);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GIF", "JPEG", "PNG" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, java.awt.BorderLayout.PAGE_START);

        jPanelSalvar.setPreferredSize(new java.awt.Dimension(415, 60));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalvarLayout = new javax.swing.GroupLayout(jPanelSalvar);
        jPanelSalvar.setLayout(jPanelSalvarLayout);
        jPanelSalvarLayout.setHorizontalGroup(
            jPanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalvarLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addGap(126, 126, 126))
        );
        jPanelSalvarLayout.setVerticalGroup(
            jPanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalvarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSalvar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jPanelSalvar, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        switch( jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).toString() ) {
            
    case "GIF":
            jTabbedPane1.setSelectedIndex(0);
            break;
    
    case "JPEG":
            jTabbedPane1.setSelectedIndex(1);
            break;
 
    case "PNG":
            jTabbedPane1.setSelectedIndex(2);
            break;
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanelGIF;
    private javax.swing.JPanel jPanelJPEG;
    private javax.swing.JPanel jPanelPNG;
    private javax.swing.JPanel jPanelSalvar;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
